{{
  config(
    materialized='incremental'
  )
}}

WITH source AS (
    SELECT * FROM {{ source('SQL_SERVER_DBO', 'ADDRESSES') }}
)

SELECT
    ADDRESS_ID,
    COALESCE(ZIPCODE, 0) AS ZIPCODE,
    COALESCE(COUNTRY, 'UNKNOWN') AS COUNTRY,
    COALESCE(ADDRESS, 'UNKNOWN') AS ADDRESS,
    COALESCE(STATE, 'UNKNOWN') AS STATE,
    CONVERT_TIMEZONE('UTC', _FIVETRAN_DELETED) AS _FIVETRAN_DELETED_UTC,
    CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED) AS _FIVETRAN_SYNCED_UTC
FROM source
;
